---
title: "class"
author: "Isheka Agarwal"
date: "9/26/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(gapminder)
library(gganimate)
```

```{r make_plot}

# Add size = pop in the aes() section to set the size of the points to be correlated to the population variable
# scale_x_log10() changes the scale of the x axis by a scale of log10
# labs(title = "title",  x = "xaxislabel", y = "yaxislabel")  changes the title, x axis labels and y axis labels respectively
# facet_wrap(~ continent) separates the plots by continent

gapminder %>% 
  filter() %>%
  filter(continent %in% c("Americas", "Africa", "Asia")) %>%
  ggplot(aes(x = gdpPercap, y = lifeExp, size = pop, alpha = 0.7, color = country)) +
  geom_point(show.legend = FALSE) +
  facet_wrap(~continent) +
  scale_x_log10(breaks = c(1000, 10000), label = c("$1000", "$10000")) +
  scale_y_continuous(limits = c(20, 85), breaks = c(40, 60, 80)) +
  scale_color_manual(values = country_colors) +
  labs(title = "World", 
       x ="GDP per capital", 
       y= "Life Expectancy") +
  transition_time(year)
```

